### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by marcusx2** [Frando/simple-local-swarm#2]
Error: listen EACCES: permission denied C:\Users\myname\AppData\Local\Temp\simple-local-swarm\8952-1.sock.

I even tried running the command window as administrator. I'm on windows.

Here's the whole error:

```
Error: listen EACCES: permission denied C:\Users\Marcus\AppData\Local\Temp\simple-local-swarm\11064-1.sock
    at Server.setupListenHandle [as _listen2] (net.js:1283:19)
    at listenInCluster (net.js:1348:12)
    at Server.listen (net.js:1447:5)
    at LocalServer._open (C:\Users\Marcus\Desktop\node_modules\simple-local-swarm\index.js:29:17)
    at LocalServer.Nanoresource.open (C:\Users\Marcus\Desktop\node_modules\nanoresource\index.js:51:8)
    at C:\Users\Marcus\Desktop\node_modules\simple-local-swarm\index.js:104:19
    at FSReqCallback.oncomplete (fs.js:146:23)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1327:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: 'C:\\Users\\Marcus\\AppData\\Local\\Temp\\simple-local-swarm\\11064-1.sock',
  port: -1
}
```

**Comment by Frando** [comment]
Interesting! I didn't test on Windows at all. If you have ideas on why the access to the socket is denied please tell. And I'll try to run it soonish on Windows. I definitely want this to work cross-platform.

**Comment by marcusx2** [comment]
No idea man, I was hoping you'd know what's going on haha. Hopefully you'll figure it out.
